apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first-k8s-deploy
  name: first-k8s-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-k8s-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-k8s-deploy
    spec:
      containers:
        - image: "sample"
          name: "sample"
          resources: {}
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
        # My readiness will be determined by envoy, but you could have this for single container deployments
        #          readinessProbe:
        #            httpGet:
        #              path: /health/ready
        #              port: 8080
        - image: "envoy"
          name: "envoy"
          resources: {}
          imagePullPolicy: Never
status: {}